### ISSUE TITLE
无法正常搭建节点

### ISSUE THREAD

**Issue by kanyways** [FISCO-BCOS/FISCO-BCOS#1166]
# 问题
按照给出的[文档部署](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html)并配置始终无法正常启动客户端。

# 系统环境
- OS:Ubuntu 16.04.3 LTS
- JDK:jdk1.8.0_231(Oracle JDK)

# 执行脚本
```bash
sudo mkdir -p /data/fisco && cd /data/fisco
sudo apt install -y openssl curl
curl -LO https://github.com/FISCO-BCOS/FISCO-BCOS/releases/download/v2.1.0/build_chain.sh && chmod u+x build_chain.sh
bash build_chain.sh -l "127.0.0.1:4" -i -p 30300,20200,8545
...
# 配置客户端，也是一步步按照文档上的描述
```

# 出现问题

```bash
Failed to connect to the node. Please check the node status and the console configuration.
```

**console/log/error.log**

```bash
[ERROR] [2019-11-12 18:22:39] BcosResponseCallback.onTimeout(17) | Processing bcos message timeout:{}
[ERROR] [2019-11-12 18:22:41] Service.run(337) | connectSeconds = 30
[ERROR] [2019-11-12 18:22:41] Service.run(338) | can not connect to nodes success, please checkout the node status and the sdk config!
[ERROR] [2019-11-12 18:22:41] Service.run(349) | system error 
java.lang.Exception: Can not connect to nodes success, please checkout the node status and the sdk config!
	at org.fisco.bcos.channel.client.Service.run(Service.java:340)
	at console.ConsoleInitializer.init(ConsoleInitializer.java:113)
	at console.ConsoleClient.main(ConsoleClient.java:41)
```

**console/log/info.log**

```bash
[INFO] [2019-11-12 18:22:38] ConnectionCallback.queryNodeVersion(207) |  query node version host: 127.0.0.1:20200, seq: 814375a3f57249ae9350f96a7dbf3436, content: {"jsonrpc":"2.0","method":"getClientVersion","params":[],"id":48}
[INFO] [2019-11-12 18:22:39] ConnectionCallback$2.onResponse(234) |  query node version timeout, content: 
[INFO] [2019-11-12 18:22:39] ConnectionCallback.subBlockNotification(338) |  send sub block notification request, seq: 126775dbe3c64a9d9b741ab9ef7ace57, content: ["_block_notify_1"]
[INFO] [2019-11-12 18:22:39] ConnectionCallback.queryBlockNumber(370) |  query block number host: 127.0.0.1:20200, seq: c6838a9e49b045d4bc0737d561fa0ef2, content: {"jsonrpc":"2.0","method":"getBlockNumber","params":[1],"id":49}
[INFO] [2019-11-12 18:22:40] ChannelConnections.reconnect(503) | try connect to: 127.0.0.1:20200
[INFO] [2019-11-12 18:22:40] ConnectionCallback.onConnect(91) |  connect 127.0.0.1:20200 success, ctx: 1475636551
[INFO] [2019-11-12 18:22:40] ConnectionCallback.queryNodeVersion(207) |  query node version host: 127.0.0.1:20200, seq: 28b2baf85fd44e2d86411ad496359060, content: {"jsonrpc":"2.0","method":"getClientVersion","params":[],"id":50}
```

> **说明**：以上的所有配置均是按照“[FISCO BCOS 技术文档](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/)”文档上的步骤来操作

# 需求

请问如何才能正确的部署？是否文档还不是最新的呢？

**Comment by kanyways** [comment]
经过其他小伙伴告知，修改`start.sh`的内容即可：

> 修改后内容如下：

```bash
if [ "${1}" == "-h" ] || [ "${1}" == "--help" ] || [ "${1}" == "help" ];then
    Usage
elif [ "${1}" == "-v" ] || [ "${1}" == "--version" ];then
    java -Djdk.tls.namedGroups="secp256k1" -cp "apps/*:conf/:lib/*:classes/" console.common.ConsoleVersion
else
   check_java
   java -Djdk.tls.namedGroups="secp256k1" -cp "apps/*:conf/:lib/*:classes/:accounts/" console.ConsoleClient $@
fi
```
