### ISSUE TITLE
RHEL7.2安装依赖遇到问题

### ISSUE THREAD

**Issue by tangvis** [FISCO-BCOS/FISCO-BCOS#122]
我使用的系统版本是RHEL7.2 x86_64。因为一键安装脚本不支持（建议兼容一下，因为和centos安装情况类似，而且企业使用也多），所以选择手动安装，但是我在执行
```shell
sudo cnpm install -g babel-cli babel-preset-es2017 ethereum-console
```
时遇到
```shell
55887 silly install printInstalled
55888 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents):
55889 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
55890 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
55890 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
55890 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
55890 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
55891 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
55891 verbose stack Exit status 1
55891 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
55891 verbose stack     at emitTwo (events.js:106:13)
55891 verbose stack     at EventEmitter.emit (events.js:191:7)
55891 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
55891 verbose stack     at emitTwo (events.js:106:13)
55891 verbose stack     at ChildProcess.emit (events.js:191:7)
55891 verbose stack     at maybeClose (internal/child_process.js:920:16)
55891 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
55892 verbose pkgid scrypt@6.0.3
55893 verbose cwd /cpic/cpicapp
55894 error Linux 3.10.0-693.5.2.el7.x86_64
55895 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "babel-cli" "babel-preset-es2017" "ethereum-console"
55896 error node v6.14.2
55897 error npm  v3.10.10
55898 error code ELIFECYCLE
55899 error scrypt@6.0.3 install: `node-gyp rebuild`
55899 error Exit status 1
55900 error Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
55900 error Make sure you have the latest version of node.js and npm installed.
55900 error If you do, this is most likely a problem with the scrypt package,
55900 error not with npm itself.
55900 error Tell the author that this fails on your system:
55900 error     node-gyp rebuild
55900 error You can get information on how to open an issue for this project with:
55900 error     npm bugs scrypt
55900 error Or if that isn't available, you can get their info via:
55900 error     npm owner ls scrypt
55900 error There is likely additional logging output above.
55901 verbose exit [ 1, true ]
```
然后我选择3个包分开装，前两个正常，但是安装第三个
```shell
cnpm install -g ethereum-console
```
的时候仍然报错。最后我选择不用国内镜像，直接执行
```shell
npm install -g ethereum-console
```
就没问题了。具体原因我没有细究。

**Comment by tangvis** [comment]
经过几次不同机器的安装，我发现2点：

1. 可以试试升级npm和nodejs的版本，换最新yum源升；
2. 好像这个报错不影响后续安装。
