### ISSUE TITLE
安装区块链浏览器最后python deploy.py installAll 出现的问题

### ISSUE THREAD

**Issue by Zombieliu** [FISCO-BCOS/FISCO-BCOS#1554]
======= server start fail!    =======
Traceback (most recent call last):
  File "deploy.py", line 66, in <module>
    do()
  File "deploy.py", line 14, in do
    commBuild.do()
  File "/root/fisco-bcos-browser/deploy/comm/build.py", line 19, in do
    startWeb()
  File "/root/fisco-bcos-browser/deploy/comm/build.py", line 208, in startWeb
    res2 = doCmd("sudo " + res["output"] + " -c " + nginx_config_dir)
  File "/root/fisco-bcos-browser/deploy/comm/utils.py", line 88, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : sudo /usr/bin/nginx -c /root/fisco-bcos-browser/deploy/comm/nginx.conf, status is 256 ,output is nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) in /root/fisco-bcos-browser/deploy/comm/nginx.conf:13

**Comment by 30CURRY3** [comment]
应该是nginx没有安装
