### ISSUE TITLE
不明原因的智能合约roll back

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/FISCO-BCOS#1741]
我在centos7上部署了一个国密版的FISCO BCOS，运行稳定。
然后使用控制台成功部署了一个HelloWorld智能合约。
问题出现在调用智能合约的时候，调用get函数，结果控制台显示如下：
```
call HelloWorld 0xf42c1988c21124ee2e570f7ed09c0fbb5dfd4774 get
The execution of the contract rolled back.
```

控制台日志：
`[ERROR] [2020-08-10 17:01:16] ConsoleClient.main(394) |  message: The execution of the contract rolled back., e: {}
org.fisco.bcos.web3j.tx.exceptions.ContractCallException: The execution of the contract rolled back.
	at org.fisco.bcos.web3j.protocol.channel.ChannelEthereumService.send(ChannelEthereumService.java:98)
	at org.fisco.bcos.web3j.protocol.core.Request.send(Request.java:90)
	at org.fisco.bcos.web3j.tx.Contract.executeCall(Contract.java:307)
	at org.fisco.bcos.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:316)
	at org.fisco.bcos.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:327)
	at org.fisco.bcos.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:482)
	at org.fisco.bcos.web3j.protocol.core.RemoteCall.send(RemoteCall.java:28)
	at console.contract.ContractImpl.call(ContractImpl.java:313)
	at console.ConsoleClient.main(ConsoleClient.java:112)
`

FISCO BCOS节点日志：
error|2020-08-10 16:47:44.086398|[TxExeError]Transaction execution error,TransactionExceptionID=22,hash=call

目前完全不知道哪里有错误。按照道理来说HelloWorld的get函数应该是最不可能出错的。但偏偏就出错了。

**Comment by lilianwen** [comment]
链是国密版的，控制台配置的时候忘记替换国密版的jar包或者替换不成功就会导致这个问题。

**Comment by bxq2011hust** [comment]
> 链是国密版的，控制台配置的时候忘记替换国密版的jar包或者替换不成功就会导致这个问题。

感谢反馈，是的，国密必须用国密的Jar包，我们会在未来的版本中优化掉国密和非国密需要替换jar包的这个操作
