### ISSUE TITLE
存证sample-合约部署出错

### ISSUE THREAD

**Issue by lingyiming** [FISCO-BCOS/FISCO-BCOS#192]
[root@test-lzq bin]# ./evidence deploy user.jks '123456' '123456'

命令输入参考如下！ 
工厂合约部署：./evidence deploy keyStoreFileName keyStorePassword keyPassword  
创建新证据：./evidence new  keyStoreFileName keyStorePassword keyPassword deployAddress evidence_id evidence_hash  
发送签名：./evidence send keyStoreFileName keyStorePassword keyPassword newEvidenceAddress evidence_hash 
获取证据：./evidence get keyStoreFileName keyStorePassword keyPassword newEvidenceAddress 
证据和签名校验：./evidence verify keyStoreFileName keyStorePassword keyPassword newEvidenceAddress 
获取公钥：./evidence getPublicKey keyStoreFileName keyStorePassword keyPassword  

java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.bcos.evidence.app.BcosApp.deployContract(BcosApp.java:82)
	at org.bcos.evidence.app.Main.main(Main.java:39)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at org.bcos.web3j.protocol.channel.ChannelEthereumService.send(ChannelEthereumService.java:56)
	at org.bcos.web3j.protocol.core.Request.send(Request.java:93)
	at org.bcos.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:129)
	at org.bcos.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:92)
	at org.bcos.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:45)
	at org.bcos.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:42)
	at org.bcos.web3j.tx.Contract.executeTransaction(Contract.java:302)
	at org.bcos.web3j.tx.Contract.create(Contract.java:434)
	at org.bcos.web3j.tx.Contract.deploy(Contract.java:409)
	at org.bcos.web3j.tx.Contract.lambda$deployAsync$4(Contract.java:451)
	at org.bcos.web3j.utils.Async.lambda$run$29(Async.java:22)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.NullPointerException
	at org.bcos.evidence.app.BcosApp.deployContract(BcosApp.java:86)
	at org.bcos.evidence.app.Main.main(Main.java:39)

**Comment by mingzhenliu** [comment]
https://github.com/FISCO-BCOS/web3sdk/wiki/web3sdk-debug   
请先按照这个排查下
