### ISSUE TITLE
存证案例调用失败,日志不足,无法定位

### ISSUE THREAD

**Issue by yi-jun** [FISCO-BCOS/FISCO-BCOS#22]
根据文档体验存证案例的时候, 失败, 连接出了问题,
但是不知是哪里出了问题, 日志显示的太少,  
无法定位具体是哪的错误.请问出现问题如何排查?

java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.bcos.evidence.app.BcosApp.deployContract(BcosApp.java:83)
	at org.bcos.evidence.app.Main.main(Main.java:49)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at org.bcos.web3j.protocol.channel.ChannelEthereumService.send(ChannelEthereumService.java:50)
	at org.bcos.web3j.protocol.core.Request.send(Request.java:69)
	at org.bcos.web3j.tx.RawTransactionManager.signAndSend(RawTransactionManager.java:106)
	at org.bcos.web3j.tx.RawTransactionManager.sendTransaction(RawTransactionManager.java:90)
	at org.bcos.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:45)
	at org.bcos.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:43)
	at org.bcos.web3j.tx.Contract.executeTransaction(Contract.java:207)
	at org.bcos.web3j.tx.Contract.create(Contract.java:309)
	at org.bcos.web3j.tx.Contract.deploy(Contract.java:284)
	at org.bcos.web3j.tx.Contract.lambda$deployAsync$25(Contract.java:326)
	at org.bcos.web3j.utils.Async.lambda$run$29(Async.java:22)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.NullPointerException
	at org.bcos.evidence.app.BcosApp.deployContract(BcosApp.java:87)
	at org.bcos.evidence.app.Main.main(Main.java:49)

**Comment by Tes99t01** [comment]
**哈哈！上述您说的这个问题我经常遇到，基本按照以下方式排除就能解决：**
1、检查配置是否连接的是channelPort，需要配置成channelPort。
2、节点listen ip是否正确，最好直接监听0.0.0.0。
3、本地开发环境检查channelPort是否能telnet通，需要能telnet通。如果不通检查网络策略，检查服务是否启动。
4、服务端和客户端ca.crt是否一致，需要一致。
5、检查keystore文件是否正确生成（具体生成步骤可参考）。


希望以上方法能对你有所帮助！

**Comment by ylij** [comment]
@Tes99t01 对的基本就是channelPort的问题
