### ISSUE TITLE
FISCO-BCOS无法创建eth账户

### ISSUE THREAD

**Issue by davidvon** [FISCO-BCOS/FISCO-BCOS#230]
- 在使用babel-node时调用合约接口时经常报：
 web3.eth.defaultAccount = config.account
> instance.newEv( "a01", "b01", "100", 101, "0x47371f625efc9953c1756e91f9ceea9e8a656d501d7ef773c1e79c2d91f9c566", "0x725f5e8b5be624301ca1722e1c69b03076c76a554f4c1881dd5862c637266e45", "0x080f6E3a15f02c552855850B20672701F2c219fF")
{ detail_info: 'callback eth_sendTransaction exceptioned, error msg:Account unknown.',
  ret_code: -1 }

- 想通过web.personal来创建帐户也失败 （web3sdk RegisterAccount Account这种创建账户方式发现两码事）
> web3.personal.listAccounts
/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/requestmanager.js:61
        throw errors.InvalidResponse(result);
        ^

Error: METHOD_NOT_FOUND: The method being requested is not available on this server
    at Object.InvalidResponse (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Personal.get [as listAccounts] (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/property.js:107:62)
    at repl:1:14
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at _eval (/usr/lib/node_modules/babel-cli/lib/_babel-node.js:99:23)
    at REPLServer.replEval (/usr/lib/node_modules/babel-cli/lib/_babel-node.js:179:14)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
> web3.personal.newAccount()
/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/requestmanager.js:61
        throw errors.InvalidResponse(result);
        ^

Error: METHOD_NOT_FOUND: The method being requested is not available on this server
    at Object.InvalidResponse (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Personal.send [as newAccount] (/home/fisco/bank1/build/tool/node_modules/web3/lib/web3/method.js:145:58)
    at repl:1:15
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at _eval (/usr/lib/node_modules/babel-cli/lib/_babel-node.js:99:23)
    at REPLServer.replEval (/usr/lib/node_modules/babel-cli/lib/_babel-node.js:179:14)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
>

**Comment by JimmyShi22** [comment]
这里和以太坊有些不同，FISCO-BCOS中，发交易的对象是机构，机构用自己的证书生成sdk证书，用作交易对象的验证。合约操作用web3sdk来操作。
具体的，account的管理已经从节点上剥离。
正确的方法是，机构要发交易，是用web3sdk发交易，在web3sdk中配置自己的sdk证书
机构的SDK证书生成：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/usage/tools.html#sdk
web3sdk用法：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/web3sdk/index.html

**Comment by joeyeeluo** [comment]
> FISCO-BCOS已经废弃了account和keystore，发交易请使用sendRawTransaction

这个sendRawTransaction传入的这个参数和以太坊有区别吗，我发现sendTransaction跟以太坊有点不一样。
