### ISSUE TITLE
引入okhttp3触发：java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1

### ISSUE THREAD

**Issue by leix101** [FISCO-BCOS/FISCO-BCOS#2333]
触发条件：项目中引入了okhttp3，并实例化client，此时sdk连接链上节点报错：
java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1
取消okhttp的初始化可正常连接，即证书配置正确。
或okhttp的初始化不引入TLS的ConnectionSpec也没有问题(仅配置ConnectionSpec.CLEARTEXT)，如下

new OkHttpClient.Builder()
.connectionSpecs(singletonList(ConnectionSpec.CLEARTEXT)).build();

报错堆栈：
2022-04-02 15:48:47.247  WARN 28163 --- [ntLoopGroup-2-1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.58.Final.jar:4.1.58.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_301]
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1793) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:777) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511) ~[na:1.8.0_301]
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1086) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:977) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1450) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        ... 17 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369) ~[na:1.8.0_301]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263) ~[na:1.8.0_301]
        at sun.security.validator.Validator.validate(Validator.java:271) ~[na:1.8.0_301]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312) ~[na:1.8.0_301]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:275) ~[na:1.8.0_301]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:140) ~[na:1.8.0_301]
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:261) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:698) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[tcnative-2.0.34.1.jar:na]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:596) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1220) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1346) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1389) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:206) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
        ... 21 common frames omitted
        Suppressed: javax.net.ssl.SSLHandshakeException: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1309) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1270) ~[netty-all-4.1.58.Final.jar:4.1.58.Final]
                ... 25 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135) ~[na:1.8.0_301]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:225) ~[na:1.8.0_301]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:145) ~[na:1.8.0_301]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84) ~[na:1.8.0_301]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[na:1.8.0_301]
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364) ~[na:1.8.0_301]
        ... 35 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on disabled algorithm: secp256k1
        at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:246) ~[na:1.8.0_301]
        at sun.security.util.DisabledAlgorithmConstraints.permits(DisabledAlgorithmConstraints.java:200) ~[na:1.8.0_301]
        at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:285) ~[na:1.8.0_301]
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125) ~[na:1.8.0_301]
        ... 40 common frames omitted

**Comment by leix101** [comment]
sdk version = '2.8.0-GMT0018'

**Comment by leix101** [comment]
@MaggieNgWu cc。把下面这部分property设置挪在okhttp初始化之前，也能解决问题。这里有其他方式加载到SslContext吗，修改全局配置的方式柑橘不太优雅，可能会对其他地方有影响？

<img width="929" alt="image" src="https://user-images.githubusercontent.com/12217063/161419362-6a836a37-e6ef-4cad-81f0-be9d876bc336.png">

**Comment by cyjseagull** [comment]
这里的问题是FISCO BCOS ssl连接采用了`secp256k1`曲线，但高版本的jdk默认disable了`secp256k1`，导致握手失败。

```java
   Security.setProperty("jdk.disabled.namedCurves", "");
   System.setProperty("jdk.sunec.disableNative", "false");
```
上面这两行代码是为了将禁用的`secp256k1`曲线打开。


sdk连接节点失败的详细排查步骤可参考[java sdk #issue536](https://github.com/FISCO-BCOS/java-sdk/issues/536)。
