### ISSUE TITLE
browser-deploy 部署报错execute cmd  error ,cmd : sed -i "s/dbUsername/root/g"

### ISSUE THREAD

**Issue by peter-jim** [FISCO-BCOS/FISCO-BCOS#2359]
我的电脑是mac M1，FISCO-BCOS 一件部署是否还不能支持，我已经安装了openssl, curl, wget, git, nginx, dos2unix依赖项目？报错信息如下：

Traceback (most recent call last):
  File "/Users/lance/browser-deploy/deploy.py", line 66, in <module>
    do()
  File "/Users/lance/browser-deploy/deploy.py", line 14, in do
    commBuild.do()
  File "/Users/lance/browser-deploy/comm/build.py", line 15, in do
    installServer()
  File "/Users/lance/browser-deploy/comm/build.py", line 79, in installServer
    changeServerConfig()
  File "/Users/lance/browser-deploy/comm/build.py", line 116, in changeServerConfig
    doCmd('sed -i "s/dbUsername/{}/g" {}/browser.sh'.format(mysql_user, script_dir))
  File "/Users/lance/browser-deploy/comm/utils.py", line 91, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : sed -i "s/dbUsername/root/g" /Users/lance/browser-deploy/server/script/browser.sh, status is 1 ,output is sed: 1: "/Users/lance/browser-de ...": extra characters at the end of l command

**Comment by userInner** [comment]
我也报了这个错误
2022-10-14 05:08:27 (76.4 MB/s) - ‘webase-web.zip’ saved [568]

Traceback (most recent call last):
  File "deploy.py", line 77, in <module>
    do()
  File "deploy.py", line 14, in do
    commBuild.do()
  File "/home/ubuntu/webase-deploy/comm/build.py", line 15, in do
    installWeb()
  File "/home/ubuntu/webase-deploy/comm/build.py", line 150, in installWeb
    pullSourceExtract(gitComm,"webase-web")
  File "/home/ubuntu/webase-deploy/comm/utils.py", line 188, in pullSourceExtract
    doCmd("unzip -o {}.zip".format(fileName))
  File "/home/ubuntu/webase-deploy/comm/utils.py", line 101, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : unzip -o webase-web.zip, status is 9 ,output is Archive:  webase-web.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of webase-web.zip or
        webase-web.zip.zip, and cannot find webase-web.zip.ZIP, period.
