### ISSUE TITLE
部署系统合约【Couldn't find preset "es2017" relative to directory】

### ISSUE THREAD

**Issue by HannibalXZX** [FISCO-BCOS/FISCO-BCOS#254]
在部署系统合约时报错

---------- Deploy system contract ----------
RUN: bash deploy_systemcontract.sh -d /home/shaw/mydata/node0 
Pre-start genesis node
Deploy System Contract
deploy_systemcontract.sh: 行 120: jq: 未找到命令
deploy_systemcontract.sh: 行 121: jq: 未找到命令
Start depoly system contract
RUN: babel-node deploy_systemcontract.js /home/shaw/mydata/FISCO-BCOS/tools/web3lib/tmp_config_deploy_system_contract.js
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2017" relative to directory "/home/shaw/mydata/FISCO-BCOS/tools/systemcontract"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)

deploy_systemcontract.sh: 行 120: jq: 未找到命令
deploy_systemcontract.sh: 行 121: jq: 未找到命令

未找到命令什么意思？

**Comment by HannibalXZX** [comment]
1、npm install --save-dev babel-preset-es2017

已自行解决
