### ISSUE TITLE
控制台3.0.0-rc4连接Pro版本 handshake timeout

### ISSUE THREAD

**Issue by WaterMan666666** [FISCO-BCOS/FISCO-BCOS#2688]
控制台连接RPC是显示 handshake timeout，

查看RPC日志：
日志显示：websocket handshake successfully 握手成功；
onRecvMessage]unrecognized message type，消息无法试别，又关闭了连接

info|2022-08-04 10:34:21.874848|[WS][SERVICE][newSession]start the session,endPoint=172.25.0.1:54743
info|2022-08-04 10:34:21.874858|[WS][SESSION][startAsServer]start websocket handshake,endPoint=172.25.0.1:54743,session=0x2ec2010
debug|2022-08-04 10:34:21.874938|[HTTP][SESSION],[DELOBJ][HTTPSESSION]=0x2254b50
debug|2022-08-04 10:34:21.874946|[HTTP][STREAM],[DELOBJ][HttpStreamSslImpl]=0x2ee6690
info|2022-08-04 10:34:21.874972|[WS][SERVICE][addSession]add session to mapping,connectedEndPoint=172.25.0.1:54743,endPoint=172.25.0.1:54743,result=true
info|2022-08-04 10:34:21.874978|[WS][SERVICE][onConnect],endpoint=172.25.0.1:54743,connectedEndPoint=172.25.0.1:54743,refCount=4
info|2022-08-04 10:34:21.874997|[WS][SESSION][onWsAccept]websocket handshake successfully,endPoint=172.25.0.1:54743,session=0x2ec2010
warning|2022-08-04 10:34:21.875569|[WS][SERVICE][onRecvMessage]unrecognized message type,type=0,endpoint=172.25.0.1:54743,seq= 73a1a195fd0c4b2aaacfd0d3bdc2,data size=51,use_count=5
info|2022-08-04 10:34:25.427433|[WS][SERVICE][heartbeat]connected nodes,count=1
debug|2022-08-04 10:34:27.101306|[EVENT][SUB][eventSubTasks]all event sub tasks subscribed by client,count=0
warning|2022-08-04 10:34:31.875951|[WS][SESSION][asyncRead],error=stream truncated,endpoint=172.25.0.1:54743,session=0x2ec2010
info|2022-08-04 10:34:31.875982|[WS][SESSION][drop],reason=4294963295,endpoint=172.25.0.1:54743,session=0x2ec2010
info|2022-08-04 10:34:31.876007|[WS][STREAM]the real action to close the stream,this=0x2eb9a80
info|2022-08-04 10:34:31.876040|[WS][SERVICE][removeSession],endpoint=172.25.0.1:54743
info|2022-08-04 10:34:31.876058|[WS][SERVICE][onDisconnect],endpoint=172.25.0.1:54743,connectedEndPoint=172.25.0.1:54743,refCount=3

**Comment by cyjseagull** [comment]
请确定pro版本区块链已经升级到`3.0.0-rc4`

**Comment by ywy2090** [comment]
发现具体的版本信息，节点跟console

**Comment by 499909744** [comment]
fisco 和console 都是 3.0.0-rc4版本，部署pro版的时候，无论是host还是bridge模式，都是启动后，tars全部正常，console连不到；前边air版本的时候console是可以的，pro版本的死活不行。
每次报这个错
`warning|2022-08-11 18:25:04.541362|[RPCWS][SERVICE][waitForConnectionEstablish]wait for websocket connection handshake timeout,timeout=30000
error|2022-08-11 18:25:04.541400|[bcos_sdk_start],sdk=0x7f490c6f3180,errorMsg=/github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout
`
telnet ip port  测试端口都是通的,证书和配置也都复制过了的

**Comment by cyjseagull** [comment]
> fisco 和console 都是 3.0.0-rc4版本，部署pro版的时候，无论是host还是bridge模式，都是启动后，tars全部正常，console连不到；前边air版本的时候console是可以的，pro版本的死活不行。 每次报这个错 `warning|2022-08-11 18:25:04.541362|[RPCWS][SERVICE][waitForConnectionEstablish]wait for websocket connection handshake timeout,timeout=30000 error|2022-08-11 18:25:04.541400|[bcos_sdk_start],sdk=0x7f490c6f3180,errorMsg=/github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish() Dynamic exception type: boost::wrapexcept<std::runtime_error> std::exception::what: The websocket connection handshake timeout ` telnet ip port 测试端口都是通的,证书和配置也都复制过了的

找到rpc、gateway、区块链节点二进制路径，运行`--version`命令确认rpc服务、区块链节点、gateway服务均升级到了`3.0.0-rc4`

**Comment by 499909744** [comment]
root@1cb9775daf80:/usr/local/app/tars/tarsnode/data/chain0.agencyABcosGatewayService/bin# ./agencyABcosGatewayService --version
FISCO BCOS Version : 3.0.0-rc4
Build Time         : 20220711 04:35:11
Build Type         : Linux/g++/Release
Git Branch         : HEAD
Git Commit         : 7208d1e81c7dc30255176682ad6b43a3c03163db

root@1cb9775daf80:/usr/local/app/tars/tarsnode/data/chain0.agencyABcosRpcService/bin# ./agencyABcosRpcService --version
FISCO BCOS Version : 3.0.0-rc3
Build Time         : 20220402 02:56:21
Build Type         : Linux/g++/Release
Git Branch         : HEAD
Git Commit         : 3d113c8acba8774f4f99e6252f40eb0bded27dec

root@1cb9775daf80:/usr/local/app/tars/tarsnode/data/chain0.agencyAgroup0node0BcosNodeService/bin# ./agencyAgroup0node0BcosNodeService --version
FISCO BCOS Version : 3.0.0-rc4
Build Time         : 20220711 04:35:11
Build Type         : Linux/g++/Release
Git Branch         : HEAD
Git Commit         : 7208d1e81c7dc30255176682ad6b43a3c03163db

按照文档安装的，这个版本还需要手动设置么，都没注意

**Comment by 499909744** [comment]
[root@centos console]# ./start.sh --version
console version: 3.0.0-rc4

**Comment by 499909744** [comment]
ok了，是因为rpc的版本【./agencyABcosRpcService --version
FISCO BCOS Version : 3.0.0-rc3】导致的。是把rpc的服务下线，删除掉宿主机上的generated中的rpc目录后，重新部署rpc后，可以连接了，

**Comment by zlcolin** [comment]
> fisco 和console 都是 3.0.0-rc4版本，部署pro版的时候，无论是host还是bridge模式，都是启动后，tars全部正常，console连不到；前边air版本的时候console是可以的，pro版本的死活不行。 每次报这个错 `warning|2022-08-11 18:25:04.541362|[RPCWS][SERVICE][waitForConnectionEstablish]wait for websocket connection handshake timeout,timeout=30000 error|2022-08-11 18:25:04.541400|[bcos_sdk_start],sdk=0x7f490c6f3180,errorMsg=/github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish() Dynamic exception type: boost::wrapexcept<std::runtime_error> std::exception::what: The websocket connection handshake timeout ` telnet ip port 测试端口都是通的,证书和配置也都复制过了的

遇到同样的问题，console]# ./start.sh 
Failed to create BcosSDK failed! Please check the node status and the console configuration, error info: get Client failed, e: /github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

**Comment by zlcolin** [comment]
> > fisco 和console 都是 3.0.0-rc4版本，部署pro版的时候，无论是host还是bridge模式，都是启动后，tars全部正常，console连不到；前边air版本的时候console是可以的，pro版本的死活不行。 每次报这个错 `warning|2022-08-11 18:25:04.541362|[RPCWS][SERVICE][waitForConnectionEstablish]wait for websocket connection handshake timeout,timeout=30000 error|2022-08-11 18:25:04.541400|[bcos_sdk_start],sdk=0x7f490c6f3180,errorMsg=/github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish() Dynamic exception type: boost::wrapexcept<std::runtime_error> std::exception::what: The websocket connection handshake timeout ` telnet ip port 测试端口都是通的,证书和配置也都复制过了的
> 
> 找到rpc、gateway、区块链节点二进制路径，运行`--version`命令确认rpc服务、区块链节点、gateway服务均升级到了`3.0.0-rc4`


2022-08-13 10:49:05.658 INFO  org.fisco.bcos.sdk.jni.rpc.RpcJniObj 27 build -- nativePointer: 140542947403664
2022-08-13 10:49:35.707 WARN  org.fisco.bcos.sdk.v3.BcosSDK 109 getClient -- create client for failed, error: org.fisco.bcos.sdk.jni.common.JniException: /github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

	at org.fisco.bcos.sdk.jni.rpc.RpcJniObj.start(Native Method) ~[bcos-sdk-jni-3.0.0-rc4.jar:?]
	at org.fisco.bcos.sdk.v3.client.ClientImpl.start(ClientImpl.java:1064) ~[fisco-bcos-java-sdk-3.0.0-rc4.jar:?]
	at org.fisco.bcos.sdk.v3.client.ClientImpl.<init>(ClientImpl.java:136) ~[fisco-bcos-java-sdk-3.0.0-rc4.jar:?]
	at org.fisco.bcos.sdk.v3.client.Client.build(Client.java:96) ~[fisco-bcos-java-sdk-3.0.0-rc4.jar:?]
	at org.fisco.bcos.sdk.v3.BcosSDK.getClient(BcosSDK.java:104) [fisco-bcos-java-sdk-3.0.0-rc4.jar:?]
	at console.ConsoleInitializer.loadAccountInfo(ConsoleInitializer.java:141) [console.jar:?]
	at console.ConsoleInitializer.init(ConsoleInitializer.java:60) [console.jar:?]
	at console.Console.main(Console.java:49) [console.jar:?]

2022-08-13 10:49:35.714 ERROR console.ConsoleInitializer 176 loadAccountInfo --  message: get Client failed, e: /github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout
, e: org.fisco.bcos.sdk.v3.BcosSDKException: get Client failed, e: /github/home/.hunter/_Base/0ba8099/8cf628f/6cc1dfe/Build/bcos-cpp-sdk/Source/bcos-cpp-sdk/ws/Service.cpp(96): Throw in function void bcos::cppsdk::service::Service::waitForConnectionEstablish()
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: The websocket connection handshake timeout

AIR版本，也有遇到同样的问题。求建议提示

**Comment by JimmyShi22** [comment]
可以用telnet线检查端口是否存在，如果存在，可以关闭ssl链接的模式（节点和console都关闭），看看是否能连上，如果可以，就是证书问题，再检查证书
