### ISSUE TITLE
升级至v3.2.0版本之后，抛出异常 transaction hash mismatching

### ISSUE THREAD

**Issue by ywy2090** [FISCO-BCOS/FISCO-BCOS#3503]
`@xxx 您好！这边已经使用了sdk3.2.0,但是还是报，能协助看下是什么原因导致？：》》》》》》》
2023-03-20 09:17:14.409 [http-nio-5002-exec-2] ERROR ExceptionsHandler() - catch  exception: []
org.fisco.bcos.sdk.v3.client.exceptions.ClientException: callRemoteMethod failed for decode the message exception, error message:ErrorMessage: /home/ci/actions-runner/_work/FISCO-BCOS/FISCO-BCOS/bcos-tars-protocol/bcos-tars-protocol/protocol/TransactionFactoryImpl.h(77): Throw in function virtual bcos::protocol::Transaction::Ptr bcostars::protocol::TransactionFactoryImpl::createTransaction(bcos::bytesConstRef, bool, bool)
Dynamic exception type: boost::wrapexcept<std::invalid_argument>
std::exception::what: transaction hash mismatching

        at org.fisco.bcos.sdk.v3.client.ClientImpl.callRemoteMethod(ClientImpl.java:1168) ~[fisco-bcos-java-sdk-3.2.0.jar:?]
        at org.fisco.bcos.sdk.v3.client.ClientImpl.sendTransaction(ClientImpl.java:232) ~[fisco-bcos-java-sdk-3.2.0.jar:?]
        at org.fisco.bcos.sdk.v3.client.ClientImpl.sendTransaction(ClientImpl.java:225) ~[fisco-bcos-java-sdk-3.2.0.jar:?]

3.2的链修改了交易的验证逻辑`

**Comment by ywy2090** [comment]
# `transaction hash mismatching`错误解决

```shell
ErrorMessage: /home/ci/actions-runner/_work/FISCO-BCOS/FISCO-BCOS/bcos-tars-protocol/bcos-tars-protocol/protocol/TransactionFactoryImpl.h(77): Throw in function virtual bcos::protocol::Transaction::Ptr bcostars::protocol::TransactionFactoryImpl::createTransaction(bcos::bytesConstRef, bool, bool)
Dynamic exception type: boost::wrapexcept<std::invalid_argument>
std::exception::what: transaction hash mismatching
```

底层区块链环境由原来的版本升级至`v3.2.0+`，或者直接使用`v3.2.0+`环境，`sdk`发送交易时，可能会出现`transaction hash mismatching`的异常

## 原因

区块链节点`v3.2.0+`新增对交易`hash`强制校验

节点检测到`sdk`发送交易结构里面携带的交易`hash`字段与节点本身计算出来的交易`hash`不匹配，认为该交易存在问题拒绝该交易。

## 场景

一般场景下不会出现该问题，仅在用户使用`sdk`提供自行组装（分别调用接口创建、计算hash、签名）交易时，可能会出现该问题

## 解决

使用正确的接口组装交易：

1. bcos_sdk_create_transaction_data
2. bcos_sdk_calc_transaction_data_hash # **注意**：一定要使用该接口计算hash
3. bcos_sdk_sign_transaction_data_hash
4. bcos_sdk_create_signed_transaction_with_signed_data

示例:
[c-sdk示例](https://github.com/FISCO-BCOS/bcos-c-sdk/blob/v3.2.0/sample/tx/hello_sample.c#L308)

各个语言的`sdk`对上述接口均有对应的封装:
    - [`Java SDK`链接](https://github.com/FISCO-BCOS/bcos-sdk-jni/blob/v3.2.0/src/main/java/org/fisco/bcos/sdk/jni/utilities/tx/TransactionBuilderJniObj.java#L21)
    - 其他语言sdk，请参考具体文档，或者源码
