### ISSUE TITLE
运行python-sdk示例代码时报错

### ISSUE THREAD

**Issue by Lorenz5622** [FISCO-BCOS/FISCO-BCOS#3642]
**问题描述**
运行python-sdk中的demo_transaction2.py时报错

**报错信息**
<img width="503" alt="image" src="https://github.com/FISCO-BCOS/FISCO-BCOS/assets/91588395/6485f966-8f80-4ef6-b766-be39c07b0495">

Traceback (most recent call last):
  File "/home/lorenz/python-sdk/demo_transaction2.py", line 33, in <module>
    Compiler.compile_file("./contracts/HelloWorld6.sol")
  File "/home/lorenz/python-sdk/client/common/compiler.py", line 112, in compile_file
    raise CompileError("compile error for compile failed, error information: {}".format(e))
client.bcoserror.CompileError: compile error for compile failed, error information: Command '['./solcjs', '--bin', '--abi', './contracts/HelloWorld6.sol', '-o', 'contracts']' returned non-zero exit status 127.

**配置环境**
Ubuntu 20.04
anaconda虚拟环境 python=3.7.5 相关配置已安装

**Comment by LucasLi1024** [comment]
看报错是系统执行指令时找不到node，请检查下
1. 是否安装了node；
2. 如果安装了node，看下是否配置路径问题。具体可参考：https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory
