### ISSUE TITLE
JAVA SDK连接报错

### ISSUE THREAD

**Issue by Taikven** [FISCO-BCOS/FISCO-BCOS#3664]
根据这个教程的基础上https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/enterprise_tools/tutorial_detail_operation.html
使用CA生成了链证书，然后让CA去生成了A,B,C,D四个机构，最后ABCD机构生成一个节点并加入群组1
我给A机构用一键部署工具生成了控制台，启动后可以正常使用
而后我用WeBASE工具连接，也可以使用。
随后我采用IDEA通过java去连接，把控制台里的ca.crt、sdk.crt、sdk.key放入项目并完成了配置进行连接，出现如下错误
（我试着连接《搭建第一个区块链网络》中生成的单机构4节点的链，是可以成功的。）
`io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(6) + length(32) exceeds writerIndex(18): PooledSlicedByteBuf(ridx: 6, widx: 18, cap: 18/18, unwrapped: PooledUnsafeDirectByteBuf(ridx: 18, widx: 18, cap: 47))
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382) [netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1256) [netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1296) [netty-handler-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.90.Final.jar:4.1.90.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]`

此外，我看了一下sdk.crt里的值有两个，不知道是不是这个原因。但是由于目标机构确实是由ca机构生成的，本就应该由两个值。我重新生成sdk目录，sdk.crt也是两个值
`cr-----BEGIN CERTIFICATE-----
MIIBxDCCAWmgAwIBAgIUO9nNWMES2qP2+0eMER1gNzvAsVcwCgYIKoZIzj0EAwIw
ODEQMA4GA1UEAwwHYWdlbmN5QTETMBEGA1UECgwKZmlzY28tYmNvczEPMA0GA1UE
CwwGYWdlbmN5MB4XDTIzMDUyNTAyNTQ1MFoXDTMzMDUyMjAyNTQ1MFowMjEMMAoG
A1UEAwwDc2RrMRMwEQYDVQQKDApmaXNjby1iY29zMQ0wCwYDVQQLDARub2RlMFYw
EAYHKoZIzj0CAQYFK4EEAAoDQgAE5a3GaxKGNe0YH+bemzt6xg7Hp101HXjYPdpJ
0LBbiwgAGZrp+HPjSK7TP7r1OXheyZ8q6zcKRLCv1bN9sL/0xaNaMFgwCQYDVR0T
BAIwADALBgNVHQ8EBAMCBeAwHQYDVR0OBBYEFEtTXSxkANU09JV9nggdLPiVKDuL
MB8GA1UdIwQYMBaAFE2eNw2HX5debuFXdjaJY5WHQ3GbMAoGCCqGSM49BAMCA0kA
MEYCIQDERscJXweb93lZvKFZ3WZ1aQz2ypPLyLrvkDa6NVAInAIhAJxbdh+bUHqD
4XFQqR4IlUb1ZN0+agMwuSum6zriSofB
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBwzCCAWmgAwIBAgIUYmYVz6lzYhcc1Rla3nnbRQ+uRGgwCgYIKoZIzj0EAwIw
PDEVMBMGA1UEAwwMZGlyX2NoYWluX2NhMRMwEQYDVQQKDApmaXNjby1iY29zMQ4w
DAYDVQQLDAVjaGFpbjAeFw0yMzA1MjQxMTIyNDhaFw0zMzA1MjExMTIyNDhaMDgx
EDAOBgNVBAMMB2FnZW5jeUExEzARBgNVBAoMCmZpc2NvLWJjb3MxDzANBgNVBAsM
BmFnZW5jeTBWMBAGByqGSM49AgEGBSuBBAAKA0IABFlYc5YRO+4uPFmiAoEnUfrO
bBoTEe40JnqSNdBT7M5rj6KgoZlRh0c8ATZs06rcwfofSmJdf19FJPRNQ+NTsbGj
UDBOMAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYEFE2eNw2HX5debuFXdjaJY5WHQ3Gb
MB8GA1UdIwQYMBaAFNLJ/n+GWKyFXF+Z2F4NFqscbucJMAoGCCqGSM49BAMCA0gA
MEUCICTV1zVMujz/kqYnYgDOS/RdJm42okKGgUzKNYxD3uwLAiEAhcfnqJsR6QjT
8zpdircgK/Z3i20yPleGixfwBbOHSzg=
-----END CERTIFICATE-----
`

**Comment by kyonRay** [comment]
Hi @Taikven 
检查一下证书是否是正确的，netty报这样的错误应该是证书格式应该是有问题的。
> cr-----BEGIN CERTIFICATE----- MIIBxDCCAWmgAwIBAgIUO9nNWMES2qP2+0eMER1gNzvAsVcwCgYIKoZIzj0EAwIw 

另外为什么这里会有`cr`开头？
