### ISSUE TITLE
Problem with deploying fisco bcos max

### ISSUE THREAD

**Issue by andrejvasilj** [FISCO-BCOS/FISCO-BCOS#3843]
Hi , the biggest question that I have is , why does my Tars service doesn't want to start when deploying max fisco bcos , do I need tars at all or not , and if I do how to I fix this.

root@fiscowebasenew1708:~/fisco/console# cd ~/fisco/console && bash start.sh
Failed to create BcosSDK failed! Please check the node status and the console configuration, error info: get Client failed, e: /github/home/.hunter/_Base/5d8365a/ac2539c/17cc295/Build/bcos-boostssl/Source/bcos-boostssl/websocket/WsService.cpp(233): Throw in function void bcos::boostssl::ws::WsService::syncConnectToEndpoints(bcos::boostssl::ws::EndPointsPtr)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: [ ssl handshake failed stream truncated:/127.0.0.1:20200,  ssl handshake failed stream [truncated:/127.0.0.1:20201]

I tried multiple times and it is not working because of this , while Pro version is easy to deploy.

Can someone assist please.

![Screenshot 2023-08-17 at 15 45 57](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/14994128/33ecfd2e-2618-4341-bcc4-82388d67088a)

**Comment by JimmyShi22** [comment]
Please make sure that tikv pd service(port 2379) has been started.

**Comment by andrejvasilj** [comment]
Hi , I did try but nothing , I get this all the time.

root@fiscobasewwe:~# cat tikv.log
[1]+  Exit 2                  tiup playground v6.5.0 --mode tikv-slim --host=172.25.0.3 -T tikv_demo --without-monitor > ~/tikv.log 2>&1  (wd: ~/fisco/BcosBuilder)
(wd now: ~)
tiup is checking updates for component playground ...timeout(2s)!
The component `playground` version  is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/playground-v1.12.5-linux-amd64.tar.gz 1.26 MiB / 8.07 MiB 15.58% ? MiB/sdownload https://tiup-mirrors.pingcap.com/playground-v1.12.5-linux-amd64.tar.gz 6.76 MiB / 8.07 MiB 83.85% ? MiB/sdownload https://tiup-mirrors.pingcap.com/playground-v1.12.5-linux-amd64.tar.gz 8.07 MiB / 8.07 MiB 100.00% 27.42 MiB/sStarting component `playground`: /root/.tiup/components/playground/v1.12.5/tiup-playground v6.5.0 --mode tikv-slim --host=172.25.0.3 -T tikv_demo --without-monitor
panic: can't get a free port

goroutine 1 [running]:
github.com/pingcap/tiup/pkg/utils.MustGetFreePort(...)
        github.com/pingcap/tiup/pkg/utils/freeport.go:41
github.com/pingcap/tiup/components/playground/instance.NewPDInstance({0x0, 0x0}, {0xc000325060, 0x1f}, {0x7ffc0d46c13c, 0xa}, {0x0, 0x0}, 0x0, 0x0)
        github.com/pingcap/tiup/components/playground/instance/pd.go:46 +0x1a5
main.(*Playground).addInstance(0xc0002ec2c0, {0x11afb49, 0x2}, {0x1367338, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, 0x1, ...})
        github.com/pingcap/tiup/components/playground/playground.go:666 +0x348
main.(*Playground).bootCluster(0xc0002ec2c0, {0x1379eb0, 0xc000283a40}, 0x1?, 0x1bca240)
        github.com/pingcap/tiup/components/playground/playground.go:902 +0x1ed1
main.execute.func3(0xc0002d0000?, {0xc0002ee000, 0x1, 0x7?})
        github.com/pingcap/tiup/components/playground/main.go:249 +0x837
github.com/spf13/cobra.(*Command).execute(0xc0002d0000, {0xc00003e090, 0x7, 0x7})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d0000)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.execute()
        github.com/pingcap/tiup/components/playground/main.go:334 +0xdfe
main.main()
        github.com/pingcap/tiup/components/playground/main.go:525 +0x3f
root@fiscobasewwe:~#

**Comment by JimmyShi22** [comment]
Hi [andrejvasilj](https://github.com/andrejvasilj)

The reason for the error "can't get a free port" is that 2379 or 2380 ports on the system are currently being used by other processes.

Or maybe... It is possible that the VPS (Virtual Private Server) has blocked or restricted access to the specific port you are trying to use. In such cases, you may need to check the server's firewall settings or contact the VPS provider to allow access to the port.

Maybe you can check using `netstat -napl|grep -iaE "2379|2380"` or `ps -ef |grep tikv`
