### ISSUE TITLE
3.6.0 air版本长期运行后节点出现异常

### ISSUE THREAD

**Issue by zh5715615** [FISCO-BCOS/FISCO-BCOS#4557]
**Describe the bug**
fisco-bcos 3.6.0 air版本，交易数量跑到900多万的时候，四个共识节点中的一个高度停止增长，其他节点业务交易上链失败，console执行deploy HelloWorld也失败，报错`deploy contract failed for callRemoteMethod failed for decode the message exception, error message:get response failed, errorCode: -4008, error message: waiting for message response timed out`

重新启动四个节点，高度异常的那个开始同步数据，高度开始增长，但速度很慢。但正常节点执行deploy HelloWorld还是报错失败了，奇怪的是交易成功了，getBlockNumber区块增长了。执行业务交易仍然报错:
```
024-07-30 01:51:11,189 [pool-3-thread-87] INFO  HandlerOnchainTask - did[did:ccid:1:0xa376dc9c419f699da63e9ed61095d93da6ecb42a], identityInfo: IdentityBean(userType=NATURE, location=430000, natureUser=NatureUserBean(phone=18273957565, certType=idcard, certNo=430521201206120164, name=???, certEffDate=null, certExpDate=null, authLevel=1), legualUser=null)
2024-07-30 01:51:11,190 [Thread-3] ERROR ClientImpl - parseResponseIntoJsonRpcResponse failed for non-empty error message, method: sendTransaction, retErrorMessage: BlockLimitCheckFail, retErrorCode: 10001
2024-07-30 01:51:11,190 [Thread-3] ERROR ClientImpl - parseResponseIntoJsonRpcResponse failed for decode the message exception, response: Response{errorCode=0, errorMessage='', content={
        "error" : 
        {
                "code" : 10001,
                "message" : "BlockLimitCheckFail"
        },
        "id" : 789,
        "jsonrpc" : "2.0"
}}, errorMessage: ErrorMessage: BlockLimitCheckFail
org.fisco.bcos.sdk.v3.client.exceptions.ClientException: ErrorMessage: BlockLimitCheckFail
        at org.fisco.bcos.sdk.v3.client.ClientImpl.parseResponseIntoJsonRpcResponse(ClientImpl.java:1440)
        at org.fisco.bcos.sdk.v3.client.ClientImpl$3.onResponse(ClientImpl.java:1330)
        at org.fisco.bcos.sdk.v3.transaction.manager.TransactionProcessor.lambda$sendTransactionAsync$0(TransactionProcessor.java:207)
2024-07-30 01:51:11,190 [Thread-3] ERROR TransactionCallback - transaction exception, errorCode: 10001, errorMessage: BlockLimitCheckFail
2024-07-30 01:51:11,190 [pool-3-thread-199] ERROR BcIdentityService - ???????[430822201203280050]????????, status = 10001, message = null
2024-07-30 01:51:11,190 [pool-3-thread-199] INFO  HandlerOnchainTask - ???????0.2
```

**To Reproduce**
1. 交易先跑到900多万，平均大概150tps的样子
2. 然后出现了一个节点异常，高度不同步
3. 重启四个节点，deploy HelloWorld还是报失败，但交易却是成功的。业务交易事件同样如此

**Expected behavior**
1.节点运行过程中，非断网断电情况下，节点不能出现数据同步异常
2.就算节点因为异常断开连接，恢复后仍能在之前的状态下继续正常运行

**Screenshots**
![微信图片_20240730103054](https://github.com/user-attachments/assets/33691c84-8f7a-42de-b313-08ce705a93f0)
![微信图片_20240730103043](https://github.com/user-attachments/assets/227dec84-dce0-4ebf-bb11-459bc0e67155)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04.4 LTS]
 - FISCO BCOS Version [e.g. 3.6.0 air]

**Comment by kyonRay** [comment]
经微信私信讨论，低版本的SDK需要手动配置sendRpcRequestToHighestBlockNode为true。此外出现超时的原因是有节点落后区块处于同步状态，在处理时有概率会触发viewchange，导致sdk超时。

**Comment by zh5715615** [comment]
问题得到解决，优化合约代码，降低合约执行时间，避免超时
