### ISSUE TITLE
JAVA SDK 预编译合约执行失败

### ISSUE THREAD

**Issue by CV-Devlau** [FISCO-BCOS/FISCO-BCOS#4602]
**Describe the bug**
版本 3.6.0 使用默认配置，使用TableCRUDService ， table 创建成功，但是 insert时失败

```
        FiscoBcos fiscoBcos = new FiscoBcos();
        fiscoBcos.init();
        BcosSDK bcosSDK = fiscoBcos.getBcosSDK();
        Client client = bcosSDK.getClient("group0");
        CryptoKeyPair cryptoKeyPair = client.getCryptoSuite().getCryptoKeyPair();
        TableCRUDService tableCRUDService = new TableCRUDService(client, cryptoKeyPair);
        // RetCode table = tableCRUDService.createTable("testTable", "user_id", Arrays.asList("username", "password"));
        // System.out.println(table);
        HashMap<String, String> objectObjectHashMap = new HashMap<>();
        objectObjectHashMap.put("user_id", "1");
        objectObjectHashMap.put("username", "1");
        objectObjectHashMap.put("password", "sdsd");
        Entry entry = new Entry(Arrays.asList("user_id","username", "password"), "2222", objectObjectHashMap);
        RetCode testTable = tableCRUDService.insert("testTable", entry);
        System.out.println(testTable);
```

## 异常信息
```
Exception in thread "main" ContractException{responseOutput=null, errorCode=15}
	at org.fisco.bcos.sdk.v3.transaction.codec.decode.ReceiptParser.getErrorStatus(ReceiptParser.java:72)
	at org.fisco.bcos.sdk.v3.contract.precompiled.crud.TableCRUDService.getCurdRetCode(TableCRUDService.java:852)
	at org.fisco.bcos.sdk.v3.contract.precompiled.crud.TableCRUDService.insert(TableCRUDService.java:416)
	at org.fisco.bcos.sdk.v3.contract.precompiled.crud.TableCRUDService.insert(TableCRUDService.java:401)
	at com.sdcdi.eda.fingerprint.EdaDriveFingerprintApplication.main(EdaDriveFingerprintApplication.java:40)
```

**Comment by CV-Devlau** [comment]
已解决：insert 时的字段与 创建表的字段不一致
