### ISSUE TITLE
2.x文档内关于使用Java SDK压力测试部分，在合约里缺少Table.sol合约

### ISSUE THREAD

**Issue by STAR-FALL-00** [FISCO-BCOS/FISCO-BCOS#4606]
- 2.x文档内关于使用Java SDK压力测试部分，在按照文档内容下载Java SDK Demo后，第四步执行示例压力测试程序，需要手动新建solidity目录，将/root/fisco/java-sdk-demo/src/main/java/org/fisco/bcos/sdk/demo/contract/sol下的合约拷贝到/root/fisco/java-sdk-demo/dist/contracts/solidity下，不然·会报错：

root@VM-16-17-ubuntu:~/fisco/java-sdk-demo/dist# java -cp "apps/*:lib/*:conf/" org.fisco.bcos.sdk.demo.codegen.DemoSolcToJava /dist/contracts/sdk/java
Exception in thread "main" java.lang.NullPointerException
        at org.fisco.bcos.sdk.demo.codegen.DemoSolcToJava.compileSolToJava(DemoSolcToJava.java:85)
        at org.fisco.bcos.sdk.demo.codegen.DemoSolcToJava.main(DemoSolcToJava.java:61)

- 并且需要从文档里下载Table.sol合约也粘贴到solidity文件夹下，不然会报错：

root@VM-16-17-ubuntu:~/fisco/java-sdk-demo/dist# java -cp "apps/*:lib/*:conf/" org.fisco.bcos.sdk.demo.codegen.DemoSolcToJava /dist/contracts/sdk/java
 Compile error: /root/fisco/java-sdk-demo/dist/contracts/solidity/TableTest.sol:4:1: Error: Source "/root/fisco/java-sdk-demo/dist/contracts/solidity/Table.sol" not found: File not found.
import "./Table.sol";
^-------------------^

**Comment by kyonRay** [comment]
应该是有缺合约接口定义，欢迎提供PR到对应仓库：https://github.com/FISCO-BCOS/java-sdk-demo

**Comment by STAR-FALL-00** [comment]
仓库里其实是有这个合约的，但是在文档“压力测试指南 — FISCO BCOS 2.0 v2.11.0 文档 (fisco-bcos-documentation.readthedocs.io)”里要求切换到“git checkout main-2.0”2.0版本，切换之后就会发现在contract文件夹下sol文件夹内的文件少了很多，缺少了Table.sol&nbsp;


袁辰洲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月2日(星期一) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FISCO-BCOS/FISCO-BCOS] 2.x文档内关于使用Java SDK压力测试部分，在合约里缺少Table.sol合约 (Issue #4606)














 
应该是有缺合约接口定义，欢迎提供PR到对应仓库：https://github.com/FISCO-BCOS/java-sdk-demo

**Comment by kyonRay** [comment]
请提供文档链接，3.0的java sdk demo和使用2.0的java sdk demo分支是不一样的。

**Comment by STAR-FALL-00** [comment]
> 请提供文档链接，3.0的java sdk demo和使用2.0的java sdk demo分支是不一样的。

链接如下：https://fisco-bcos-documentation.readthedocs.io/zh-cn/latest/docs/tutorial/stress_testing.html
