### ISSUE TITLE
python3 deploy.py installWeBASE可视化部署webase失败

### ISSUE THREAD

**Issue by 123456wzm** [FISCO-BCOS/FISCO-BCOS#4710]
root@shangwu:~/tools/webase-tools/webase-deploy# python3 deploy.py installWeBASE
============================================================

              _    _     ______  ___  _____ _____
             | |  | |    | ___ \/ _ \/  ___|  ___|
             | |  | | ___| |_/ / /_\ \ `--.| |__
             | |/\| |/ _ | ___ |  _  |`--. |  __|
             \  /\  |  __| |_/ | | | /\__/ | |___
              \/  \/ \___\____/\_| |_\____/\____/

============================================================
==============      checking envrionment      ==============
check git...
check finished sucessfully.
check openssl...
check finished sucessfully.
check curl...
check finished sucessfully.
check wget...
check finished sucessfully.
check dos2unix...
check finished sucessfully.
check Docker...
Try to start Docker...
check finished sucessfully.
check nginx...
check finished sucessfully.
check java...
check finished sucessfully.
check WeBASE-Web port...
check finished sucessfully.
check WeBASE-Node-Manager port...
check finished sucessfully.
check WeBASE-Sign IP for visual deploy...
check finished sucessfully.
check WeBASE-Sign port...
check finished sucessfully.
check database connection...
check finished sucessfully.
check database connection...
check finished sucessfully.
check mgr database user/password...
check finished sucessfully.
check sign database user/password...
check finished sucessfully.
check mgr mysql version...
node-mgr's mysql version is [5.6.16-1~exp1]
check finished sucessfully.
check sign mysql version...
sign's mysql version is [5.6.16-1~exp1]
check finished sucessfully.
==============      envrionment available     ==============
============================================================
==============        starting  deploy        ==============
============================================================
============ Download docker image from CDN... =============
wget https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/WeBASE/releases/download/v1.5.5/docker-fisco-webase.tar
--2024-11-10 19:30:45--  https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/WeBASE/releases/download/v1.5.5/docker-fis                 co-webase.tar
Resolving osp-1257653870.cos.ap-guangzhou.myqcloud.com (osp-1257653870.cos.ap-guangzhou.myqcloud.com)... 112.49.57.235,                  112.49.14.151
Connecting to osp-1257653870.cos.ap-guangzhou.myqcloud.com (osp-1257653870.cos.ap-guangzhou.myqcloud.com)|112.49.57.235|                 :443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-11-10 19:30:45 ERROR 403: Forbidden.

Traceback (most recent call last):
  File "/root/tools/webase-tools/webase-deploy/deploy.py", line 127, in <module>
    do()
  File "/root/tools/webase-tools/webase-deploy/deploy.py", line 34, in do
    commBuild.visual_do()
  File "/root/tools/webase-tools/webase-deploy/comm/build.py", line 43, in visual_do
    installDockerImage()
  File "/root/tools/webase-tools/webase-deploy/comm/build.py", line 714, in installDockerImage
    pullDockerImage(gitComm,"docker-fisco-webase.tar","fiscoorg/fisco-webase")
  File "/root/tools/webase-tools/webase-deploy/comm/utils.py", line 239, in pullDockerImage
    doCmd("docker load -i {}".format(fileName))
  File "/root/tools/webase-tools/webase-deploy/comm/utils.py", line 111, in doCmd
    raise Exception("execute cmd  error ,cmd : {}, status is {} ,output is {}".format(cmd,status, output))
Exception: execute cmd  error ,cmd : docker load -i docker-fisco-webase.tar, status is 1 ,output is open docker-fisco-we                 base.tar: no such file or directory
<img width="743" alt="Snipaste_2024-11-10_19-56-37" src="https://github.com/user-attachments/assets/43ca46de-c71e-4dd8-9514-ed093a96c9a8">

**Comment by JimmyShi22** [comment]
@CodingCattwo

**Comment by cocacola688** [comment]
你好，麻烦问一下解决了没有，我也遇到了这个问题
