### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: General SSLEngine problem

### ISSUE THREAD

**Issue by zhige2003** [FISCO-BCOS/FISCO-BCOS#89]
我使用web3sdk的源代码建立web工程，利用节点生成的client.keystore文件，并放在了classes路径下，启动的时候，提示下面的内容，请大神看看是什么原因。谢谢
01:12:07.674 DEBUG org.bcos.channel.client.Service$ConnectionCallback 74 onConnect - 已建立连接，将topic发送到该连接:60ead22418294a009eddd53e12be293d
01:12:07.675 DEBUG org.bcos.channel.client.Service$ConnectionCallback 78 onConnect - topics: []
01:12:07.679 ERROR org.bcos.channel.handler.ChannelHandler 147 exceptionCaught - 网络错误 io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.15.Final.jar:4.1.15.Final]

**Comment by fisco-dev** [comment]
可参考这里：https://github.com/FISCO-BCOS/web3sdk/issues/20

**Comment by bxq2011hust** [comment]
长时间没有回复，关闭issue。如果问题没有解决，非常欢迎再次打开
